modules: lvgl: fix multiple LVGL input nodes (gschwaer: already in main)
The input callback does not use an instance specific name, so we can only
every have one instanct of this type. This issue was evident by a build
error, e.g., when using "zephyr,lvgl-keypad-input" nodes twice:

  /path/to/include/zephyr/input/input.h:159:37: error: redefinition of '_input_callback__lvgl_keypad_process_event'
    159 |                                     _input_callback__##_callback)
        |                                     ^~~~~~~~~~~~~~~~~

Signed-off-by: Gero Schwäricke <gero.schwaericke@posteo.de>